package aplicacion.modelo.dominio;
// Generated 21/06/2018 23:28:52 by Hibernate Tools 4.3.1




/**
 * Butaca generated by hbm2java
 */
public class Butaca  implements java.io.Serializable {


     private Integer butCodigo;
     private Sala salas;
     private String butIdentificador;
     private boolean butEstado;

    public Butaca() {
    }

    public Butaca(Sala salas, String butIdentificador, boolean butEstado) {
       this.salas = salas;
       this.butIdentificador = butIdentificador;
       this.butEstado = butEstado;
    }
   
    public Integer getButCodigo() {
        return this.butCodigo;
    }
    
    public void setButCodigo(Integer butCodigo) {
        this.butCodigo = butCodigo;
    }
    public Sala getSalas() {
        return this.salas;
    }
    
    public void setSalas(Sala salas) {
        this.salas = salas;
    }
    public String getButIdentificador() {
        return this.butIdentificador;
    }
    
    public void setButIdentificador(String butIdentificador) {
        this.butIdentificador = butIdentificador;
    }
    public boolean isButEstado() {
        return this.butEstado;
    }
    
    public void setButEstado(boolean butEstado) {
        this.butEstado = butEstado;
    }




}


