package aplicacion.modelo.dominio;
// Generated 21/06/2018 23:28:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 *ButacaCarteleras generated by hbm2java
 */
public class ButacaCartelera  implements java.io.Serializable {


     private Integer bcCodigo;
     private Cartelera cartelera;
     private String bcIdentificadorButaca;
     private boolean bcDisponible;
     private boolean bcEstado;
     

    public ButacaCartelera() {
    }

	
    public ButacaCartelera(Cartelera cartelera, String bcIdentificadorButaca, boolean bcDisponible, boolean bcEstado) {
        this.cartelera = cartelera;
        this.bcIdentificadorButaca = bcIdentificadorButaca;
        this.bcDisponible = bcDisponible;
        this.bcEstado = bcEstado;
    }
    
    public Integer getBcCodigo() {
        return this.bcCodigo;
    }
    
    public void setBcCodigo(Integer bcCodigo) {
        this.bcCodigo = bcCodigo;
    }
    public Cartelera getCartelera() {
        return this.cartelera;
    }
    
    public void setCarteleras(Cartelera carteleras) {
        this.cartelera = carteleras;
    }
    public String getBcIdentificadorButaca() {
        return this.bcIdentificadorButaca;
    }
    
    public void setBcIdentificadorButaca(String bcIdentificadorButaca) {
        this.bcIdentificadorButaca = bcIdentificadorButaca;
    }
    public boolean isBcDisponible() {
        return this.bcDisponible;
    }
    
    public void setBcDisponible(boolean bcDisponible) {
        this.bcDisponible = bcDisponible;
    }
    public boolean isBcEstado() {
        return this.bcEstado;
    }
    
    public void setBcEstado(boolean bcEstado) {
        this.bcEstado = bcEstado;
    }




}


