package aplicacion.modelo.dominio;
// Generated 21/06/2018 23:28:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 *Carteleras generated by hbm2java
 */
public class Cartelera  implements java.io.Serializable {


     private Integer carCodigo;
     private Pelicula peliculas;
     private Sala salas;
     private Date carFecha;
     private String carHorario;
     private double carPrecio;
     private boolean carEstado;
     

    public Cartelera() {
    }

	
    public Cartelera(Pelicula peliculas, Sala salas, Date carFecha, String carHorario, double carPrecio, boolean carEstado) {
        this.peliculas = peliculas;
        this.salas = salas;
        this.carFecha = carFecha;
        this.carHorario = carHorario;
        this.carPrecio = carPrecio;
        this.carEstado = carEstado;
    }
    
   
    public Integer getCarCodigo() {
        return this.carCodigo;
    }
    
    public void setCarCodigo(Integer carCodigo) {
        this.carCodigo = carCodigo;
    }
    public Pelicula getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Pelicula peliculas) {
        this.peliculas = peliculas;
    }
    public Sala getSalas() {
        return this.salas;
    }
    
    public void setSalas(Sala salas) {
        this.salas = salas;
    }
    public Date getCarFecha() {
        return this.carFecha;
    }
    
    public void setCarFecha(Date carFecha) {
        this.carFecha = carFecha;
    }
    public String getCarHorario() {
        return this.carHorario;
    }
    
    public void setCarHorario(String carHorario) {
        this.carHorario = carHorario;
    }
    public double getCarPrecio() {
        return this.carPrecio;
    }
    
    public void setCarPrecio(double carPrecio) {
        this.carPrecio = carPrecio;
    }
    public boolean isCarEstado() {
        return this.carEstado;
    }
    
    public void setCarEstado(boolean carEstado) {
        this.carEstado = carEstado;
    }




}


