package aplicacion.modelo.dominio;
// Generated 21/06/2018 23:28:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 *Clasificacions generated by hbm2java
 */
public class Clasificacion  implements java.io.Serializable {


     private Integer claCodigo;
     private String claDescripcion;
     private boolean claEstado;
     

    public Clasificacion() {
    }

	
    public Clasificacion(String claDescripcion, boolean claEstado) {
        this.claDescripcion = claDescripcion;
        this.claEstado = claEstado;
    }
    
    public Integer getClaCodigo() {
        return this.claCodigo;
    }
    
    public void setClaCodigo(Integer claCodigo) {
        this.claCodigo = claCodigo;
    }
    public String getClaDescripcion() {
        return this.claDescripcion;
    }
    
    public void setClaDescripcion(String claDescripcion) {
        this.claDescripcion = claDescripcion;
    }
    public boolean isClaEstado() {
        return this.claEstado;
    }
    
    public void setClaEstado(boolean claEstado) {
        this.claEstado = claEstado;
    }
   




}


