package aplicacion.modelo.dominio;
// Generated 21/06/2018 23:28:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 *Directors generated by hbm2java
 */
public class Director  implements java.io.Serializable {


     private Integer dirCodigo;
     private String dirApellidos;
     private String dirNombres;
     private boolean dirEstado;
    

    public Director() {
    }

	
    public Director(String dirApellidos, String dirNombres, boolean dirEstado) {
        this.dirApellidos = dirApellidos;
        this.dirNombres = dirNombres;
        this.dirEstado = dirEstado;
    }
    
    public Integer getDirCodigo() {
        return this.dirCodigo;
    }
    
    public void setDirCodigo(Integer dirCodigo) {
        this.dirCodigo = dirCodigo;
    }
    public String getDirApellidos() {
        return this.dirApellidos;
    }
    
    public void setDirApellidos(String dirApellidos) {
        this.dirApellidos = dirApellidos;
    }
    public String getDirNombres() {
        return this.dirNombres;
    }
    
    public void setDirNombres(String dirNombres) {
        this.dirNombres = dirNombres;
    }
    public boolean isDirEstado() {
        return this.dirEstado;
    }
    
    public void setDirEstado(boolean dirEstado) {
        this.dirEstado = dirEstado;
    }
   




}


