package aplicacion.modelo.dominio;
// Generated 21/06/2018 23:28:52 by Hibernate Tools 4.3.1

import aplicacion.modelo.dominio.Cartelera;




/**
 * PrecioCartelera generated by hbm2java
 */
public class PrecioCartelera  implements java.io.Serializable {


     private Integer preCodigo;
     private Cartelera carteleras;
     private String preDescripcion;
     private double prePrecio;

    public PrecioCartelera() {
    }

    public PrecioCartelera(Cartelera carteleras, String preDescripcion, double prePrecio) {
       this.carteleras = carteleras;
       this.preDescripcion = preDescripcion;
       this.prePrecio = prePrecio;
    }
   
    public Integer getPreCodigo() {
        return this.preCodigo;
    }
    
    public void setPreCodigo(Integer preCodigo) {
        this.preCodigo = preCodigo;
    }
    public Cartelera getCarteleras() {
        return this.carteleras;
    }
    
    public void setCarteleras(Cartelera carteleras) {
        this.carteleras = carteleras;
    }
    public String getPreDescripcion() {
        return this.preDescripcion;
    }
    
    public void setPreDescripcion(String preDescripcion) {
        this.preDescripcion = preDescripcion;
    }
    public double getPrePrecio() {
        return this.prePrecio;
    }
    
    public void setPrePrecio(double prePrecio) {
        this.prePrecio = prePrecio;
    }




}


