package aplicacion.modelo.dominio;
// Generated 21/06/2018 23:28:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 *Salas generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private Integer salCodigo;
     private String salNombre;
     private String salDescripcion;
     private boolean salEstado;
     

    public Sala() {
    }

	
    public Sala(String salNombre, String salDescripcion, boolean salEstado) {
        this.salNombre = salNombre;
        this.salDescripcion = salDescripcion;
        this.salEstado = salEstado;
    }
    
   
    public Integer getSalCodigo() {
        return this.salCodigo;
    }
    
    public void setSalCodigo(Integer salCodigo) {
        this.salCodigo = salCodigo;
    }
    public String getSalNombre() {
        return this.salNombre;
    }
    
    public void setSalNombre(String salNombre) {
        this.salNombre = salNombre;
    }
    public String getSalDescripcion() {
        return this.salDescripcion;
    }
    
    public void setSalDescripcion(String salDescripcion) {
        this.salDescripcion = salDescripcion;
    }
    public boolean isSalEstado() {
        return this.salEstado;
    }
    
    public void setSalEstado(boolean salEstado) {
        this.salEstado = salEstado;
    }
    




}


